
name: 'sushi'
version: '1.0.0'
config-version: 2
profile: 'sushi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  +start: Jan 1 2022
  sushi:
    +materialized: table
  customers:
    +materialized: table

vars:
  top_waiters_limit: 10
  customers:customer_id: "customer_id"

  # The following are only used for testing purposes
  customers:boo: ["a", "b"]

  customers:
    some_var: ["foo", "bar"]
    'customers:bla': false
