/* Table of revenue generated by waiters by day. */
MODEL (
  name sushi.waiter_revenue_by_day,
  kind incremental_by_time_range (
    time_column date,
    batch_size 10,
  ),
  owner jen,
  cron '@daily',
  audits (
    NUMBER_OF_ROWS(threshold=0)
  ),
  grain (waiter_id, date)
);

SELECT
  o.waiter_id::INT AS waiter_id, /* Waiter id */
  SUM(oi.quantity * i.price)::DOUBLE AS revenue, /* Revenue from orders taken by this waiter */
  o.date::DATE AS date /* Date */
FROM sushi.orders AS o
LEFT JOIN sushi.order_items AS oi
  ON o.id = oi.order_id AND o.date = oi.date
LEFT JOIN sushi.items AS i
  ON oi.item_id = i.id AND oi.date = i.date
WHERE
  o.date BETWEEN @start_date AND @end_date
GROUP BY
  o.waiter_id,
  o.date
