name: 'silver'

config-version: 2
version: '0.1'

profile: 'silver'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]


models:
  start: "2024-01-01"
  +materialized: table
