project: sqlmesh_repo

gateways:
  prod:
    connection:
      type: duckdb
      database: prod.duckdb
  memory:
    connection:
      type: duckdb

default_gateway: prod

model_defaults:
  dialect: duckdb
