name: 'dbt_repo'

version: '1.0.0'

profile: 'dbt_repo'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
    - "target"
    - "dbt_packages"

models:
  dbt_repo:
    +materialized: view
    
  +start: Jan 1 2000