# Username and password are stored in ~/.sqlmesh/config.yaml
gateways:
    snowflake:
        connection:
            type: snowflake
            account: datacoves-main
            warehouse: WH_TRANSFORMING_SQLMESH
            database: SUSHI_DB
            role: SQLMESH_ANALYST
            user: env("USERNAME")
    airflow:
        connection:
            type: snowflake
            account: datacoves-main
            warehouse: WH_TRANSFORMING_SQLMESH
            database: SUSHI_DB
            role: SQLMESH_ANALYST
            user: env("USERNAME")
            password: env("USERNAME")


default_gateway: snowflake

model_defaults:
    dialect: snowflake

cicd_bot:
    type: github
