version: 2

models:
  - name: items
  - name: orders
  - name: order_items
  - name: customers
  - name: waiters
sources:
  - name: raw
    config:
      schema: sushi_raw
    tables:
      - name: orders
      - name: order_items