{{- if and .Values.secrets.externalSecrets.enabled .Values.secrets.externalSecrets.secretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "hybrid-executors.fullname" . }}-external-secrets
  labels:
    {{- include "hybrid-executors.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "hybrid-executors.fullname" . }}-external-secrets
  data:
    - secretKey: TCLOUD_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secrets.externalSecrets.keyPrefix | default "" }}tcloud-client-secret
    
    {{- range $gatewayName, $gateway := .Values.global.sqlmesh.gateways }}
      {{- range $paramName, $paramValue := $gateway.connection }}
        {{- $isSecret := include "hybrid-executors.isSecretParam" $paramName }}
        
        {{- /* Override based on secretParams if specified */}}
        {{- if $.Values.global.sqlmesh.secretParams }}
          {{- range $.Values.global.sqlmesh.secretParams }}
            {{- if eq . $paramName }}
              {{- $isSecret = "true" }}
            {{- end }}
          {{- end }}
        {{- end }}
        
        {{- /* Override based on nonSecretParams if specified */}}
        {{- if $.Values.global.sqlmesh.nonSecretParams }}
          {{- range $.Values.global.sqlmesh.nonSecretParams }}
            {{- if eq . $paramName }}
              {{- $isSecret = "false" }}
            {{- end }}
          {{- end }}
        {{- end }}
        
        {{- if eq $isSecret "true" }}
    - secretKey: {{ printf "SQLMESH__GATEWAYS__%s__CONNECTION__%s" $gatewayName (upper $paramName) }}
      remoteRef:
        key: {{ $.Values.secrets.externalSecrets.keyPrefix | default "" }}sqlmesh-gateway-{{ $gatewayName | lower }}-{{ $paramName | lower }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }} 